name: Deploy to Stage

on:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: harmony-stage

    steps:
      - name: Recreate frontend container
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/${{ secrets.DEPLOYMENT }}
            docker compose --env-file .env.stage -f harmony.yml up --detach --no-deps --force-recreate frontend
